---
    - name: Was NodeJS installed?
      stat:
        path: /usr/bin/node
      ignore_errors: true
      register: node

    - name: Was npm installed
      stat:
        path: /ust/bin/npm
      ignore_errors: true
      register: npm

    - name: debug
      debug:
        var: npm
    
    - name: Install NodeJS
      import_tasks: installnodejs.yml
