---
    - name: Git-role |  Git clone
      git:
        repo: https://github.com/hencezze/stoled-nodejs-repo.git
        dest: '{{ git_repo }}'

    - name: Git-role | Install packages from package.json
      command: chdir={{ git_repo }} npm install package.json

    - name: Git-role | Start server with NodeJS helps
      command: chdir={{ git_repo }} node index.js >> /dev/null
 
    - name: Git-role | Check server status
      uri:
        url: http://localhost:3000
